[package]
name = "snek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = "0.20.2"
indexmap = "1.8.0"
rand = "0.8.4"
